tasks:
  default:
    onboard_world: MessengerBotChatCovidWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    covid90M:
      model: transformer/generator
      model_file: zoo:covid/covid90M
      interactive_mode: True
      no_cuda: False
additional_args:
  page_id: 1 # Configure Your Own Page
